defaultWorldBorderRadius: 5000
# Zone radius (blocks)
zones: [1000, 750, 500, 350, 250, 100]
# Zone duration (seconds) (the amount of time it will take to reach the corresponding zone after the previous one) (first time is between defaultWorldBorderRadius and first zone)
times: [1500, 1200, 900, 600, 300, 200]
# Timeout between zones (seconds) (amount of zones + 1) (first timeOut is between defaultWorldBorderRadius and first zone)
timeOuts: [1800, 750, 600, 450, 300, 150, 100]
# Final zone time (Seconds)
finalZoneMoveDuration: 120
minFinalZoneMove: 50
maxFinalZoneMove: 100
zoneMoveTimeOut: 10
startBoxX: 100
startBoxY: 200
startBoxZ: 60
betterLogging: false